#+ summary: Events a person attended
#+ tags: 
#+   - event

PREFIX schema: <http://schema.org/>
PREFIX owl: <http://www.w3.org/2002/07/owl#>
SELECT ?event
WHERE {
  ?event schema:attendee/schema:attendee/owl:sameAs ?_person_iri .
}
