#+ summary: Events a person attended
#+ tags: 
#+   - event

PREFIX schema: <http://schema.org/>
SELECT ?event
FROM <http://data.cubiss.nl/genealogy/>
WHERE {
  ?event schema:attendee/schema:attendee ?person .
}
LIMIT 100
